database:
  host: "![/lCRNAhcTKfYCrY/dO2+BegZu6kOJk7Fn6O/4tCklW4UMBtOXN9POsUUUgw0BZSQs3w98PRm+zGvNkmgLU71rA==]"
  port: "![OVHIkT8xUXqffNteYz4ixg==]"
  databaseName: "![SHPbZJseOJu2z0l/npTWZQ==]"
  password: "![kTeSBQcdLDuuMayG25kQAA==]"
  username: "![OacdLFQyiHCEsD3xj/XQYw==]"
http:
  host: "0.0.0.0"
  port: "8082"
  