#%RAML 1.0 NamedExample
value:
  message: Hi Pratik, your tickets are booked now!!
  carBookingDetails:
    partner: uber
    source: bhugaon
    destination: vimannagar
    firstname: Pratik
    lastname: Thorat
    NoOfSeats: 5
    price: 200
    scheduledDate: 2021-11-12
    scheduledTime: 05:30:00        
  
